config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: [:show, :edit, :new] do
    resource :profiles, only: [:show, :edit]
    resource :addresses, only: [:new,:edit,:create]
    collection do
      get 'address'
      get 'card'
      get 'telephone'
      get 'complete'
    end
    member do
      get 'logout'
      patch 'logout'
    end
    resource :cards, only: [:show, :new] do
      collection do
        post "pay", to: "cards#pay"
        post "delete", to: "cards#delete"
      end
    end
  end

  resources :items do
    get "search", on: :collection
    member do
      patch 'stop'
    end
    resources :images
    resources :likes
    resources :comments
    resources :buy_orders, only: :new do
      collection do
        post 'index', to: 'buy_orders#pay'
        post 'pay', to: "buy_order#pay"
      end
    end
  end
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end

  resources :categories, only: :index
end

app/models/item.rb
class Item < ApplicationRecord

  enum size: {unanswered: 0, XXS: 1, XS: 2, S: 3, M: 4, L: 5, XL: 6, "2XL": 7, "3XL": 8, "4XL": 9, two_three: 10, two_three_five: 11, two_four: 12, two_four_five: 13, two_five: 14, two_five_five: 15, two_six: 16, two_six_five: 17, two_seven: 18, two_seven_five: 19, two_eight: 20, two_eight_five: 21, two_nine: 22, two_nine_five: 23, three_zero: 24, three_zero_five: 25, three_one: 26}
  enum condition: {new_item: 1, new_like: 2, no_dirt: 3, less_dirt: 4, dirt: 5, bad: 6}
  enum postage: {seller_cost: 1, buyer_cost: 2}
  enum shipping_method: {mitei: 1, rakuraku: 2, yuu: 3, letter: 4, normal: 5, cat: 6, pack: 7, post: 8, packet: 9}
  enum region: {hokkaido: 0, aomori: 1, iwate: 2, miyagi: 3, akita: 4,yamagata: 5,fukushima: 6,ibaraki: 7,tochigi: 8,gunma: 9,saitama: 10,chiba: 11,tokyo: 12,kanagawa: 13,nigata: 14,toyama: 15,ishikawa: 16,fukui: 17,yamanashi: 18,nagano: 19,gifu: 20,sizuoka: 21,aichi: 22,mie: 23,shiga: 24,kyoto: 25,osaka: 26,hyogo: 27,nara: 28,wakayama: 29,tottori: 30,shimane: 31,okayama: 32,hiroshima: 33,yamaguchi: 34,tokushima: 35,kagawa: 36,ehime: 37,kochi: 38,fukuoka: 39,saga: 40,nagasaki: 41,kumamoto: 42,oita: 43,miyazaki: 44,kagoshima: 45,okinawa: 46}
  enum shipping_date: {two: 1, three: 2, seven: 3}

  belongs_to :saler, class_name: "User", optional: true
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :category, optional: true
  has_many :images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :buy_order
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :reject_image
  attribute :parent_category_id
  attribute :child_category_id

  def reject_image(attributes)
    if attributes[:id]
      attributes.merge!(_destroy: "1") if attributes[:image_cache].blank? && attributes[:image].blank?
      false
    else
      false
    end
  end

  def like_user(id)
    likes.find_by(user_id: id)
  end

  with_options presence: true do
    validates :name
    validates :description
    validates :category_id
    validates :condition
    validates :saler
    validates :postage
    validates :shipping_method
    validates :region
    validates :shipping_date
    validates :images
  end
  validates :price, presence: true, numericality: {only_integer: true, greater_than: 299, less_than: 10000000}

  scope :item_num, -> (num) {where(category_id: num).order('id DESC').limit(4)}
  scope :item_num2, -> (num) {where(category_id: num).order('id DESC').limit(3)}
  scope :item_num3, -> (num) {where(category_id: num).order('id DESC').limit(2)}
  scope :item_brand, -> (name) {where(brand: name).order('id DESC').limit(4)}
  scope :item_brand2, -> (name) {where(brand: name).order('id DESC').limit(3)}
  scope :item_brand3, -> (name) {where(brand: name).order('id DESC').limit(2)}
  scope :recent, -> {order('id ASC')}
  scope :recent, -> {order('updated_at DESC')}
  scope :on_sale, -> {where(status: 0)}

  ransacker :likes_count do
    query = '(SELECT COUNT(likes.item_id) FROM likes where likes.item_id = items.id GROUP BY likes.item_id)'
    Arel.sql(query)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  include CommonActions
  before_action :set_item, only: [:show, :destroy, :edit, :update, :stop]
  before_action :move_to_sign_in, only: [:new, :edit, :create, :update, :destroy, :stop]
  layout 'item_application', only: [:new, :edit]
  
    def index

      @items = Item.all.where.not(status: true)
      @items_lady =  @items.item_num(ladies_category)
      @items_lady2 =  @items.item_num2(ladies_category)
      @items_lady3 =  @items.item_num3(ladies_category)

      @items_men =  @items.item_num(mens_category)
      @items_men2 =  @items.item_num2(mens_category)
      @items_men3 =  @items.item_num3(mens_category)

      @items_baby =  @items.item_num(baby_category)
      @items_baby2 =  @items.item_num2(baby_category)
      @items_baby3 =  @items.item_num3(baby_category)

      @items_cosme =  @items.item_num(cosmes_category)
      @items_cosme2 =  @items.item_num2(cosmes_category)
      @items_cosme3 =  @items.item_num3(cosmes_category)

      @items_Chanel = @items.item_brand("シャネル")
      @items_Chanel2 = @items.item_brand2("シャネル")
      @items_Chanel3 = @items.item_brand3("シャネル")

      @items_Louis_Vuitton = @items.item_brand("ルイヴィトン")
      @items_Louis_Vuitton2 = @items.item_brand2("ルイヴィトン")
      @items_Louis_Vuitton3 = @items.item_brand3("ルイヴィトン")

      @items_Supream= @items.item_brand("シュプリーム")
      @items_Supream2= @items.item_brand2("シュプリーム")
      @items_Supream3= @items.item_brand3("シュプリーム")

      @items_Nike= @items.item_brand("ナイキ")
      @items_Nike2= @items.item_brand2("ナイキ")
      @items_Nike3= @items.item_brand3("ナイキ")

    end

  def new
    @item = Item.new
    10.times do
      @item.images.build
    end
    @parent_categories = Category.child_num(0)
    @child_categories, @grandchild_categories = [], []
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item
    else
      @parent_categories = Category.where(parent_id: 0)
      @child_categories, @grandchild_categories = [], []
      redirect_to action: 'new'
    end
  end

  def edit
    grandchild_category = @item.category
    child_category = grandchild_category.parent
    parent_category = child_category.parent

    @item.parent_category_id = parent_category.id
    @item.child_category_id = child_category.id

    @grandchild_categories = child_category.children
    @child_categories = parent_category.children
    @parent_categories = Category.child_num(0)

    @item.images.each do |image|
      image.image.cache!
    end

    empty_drop_zone = 10 - @item.images.length
    empty_drop_zone.times do 
      @item.images.build
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item
    else
      redirect_to action: 'edit'
    end
  end

  def show
    @items = Item.find(params[:id])
    @slaer_items = Item.where(saler_id: @items.saler.id)

    @users = @item.saler
    @groundchild = Category.find(@item.category_id)
    @child = Category.find(@groundchild.parent_id)
    @theparent = Category.find(@child.parent_id)
  end

  def destroy
    if @item.saler_id == current_user.id
      @item.destroy
    end
    redirect_to action: :index
  end

  def stop
    @item.update(status: params[:status])
    redirect_to action: :show
  end

  def search
    if params[:keyword].present?
      @search = Item.ransack(name_or_description_cont: params[:keyword])
      @items = @search.result.on_sale
    elsif params[:q].present?
      @search = Item.ransack(search_params)
      @items = @search.result.on_sale
      @parent_category_id = params[:q][:parent_category_id]
      @child_category_id = params[:q][:child_category_id]
      @child_categories = Category.child_num(@parent_category_id)
      @grandchild_categories = Category.child_num(@child_category_id)
    end
    params[:q] ||= {sorts: 'id desc'}
    @items ||= Item.on_sale.recent
    @search ||= Item.ransack()
    @parent_categories = Category.child_num(0)
    @parent_category_id ||= ''
    @child_category_id ||= ''
    @child_categories ||= []
    @grandchild_categories ||= []
  end

  private
  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end

  def item_params
    params.require(:item).permit(:name, :description, :brand, :size, :category_id, :price, :postage, :shipping_method, :region, :shipping_date, :condition, images_attributes: [:image, :image_cache, :id, :_destroy]).merge(saler: current_user)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def search_params
    params.require(:q).permit(:sorts, :name_or_description_cont, :brand_cont, :size_eq, :price_gteq, :price_lteq, { condition_eq_any: [] }, { postage_eq_any: [] }).merge(search_categories_params).merge(buyer_id_params)
  end

  def search_categories_params
    if params[:q][:category_id_eq_any].present?
      grandchild_category_ids = params[:q][:category_id_eq_any]
    elsif params[:q][:child_category_id].present?
      grandchild_category_ids = Category.child_num(params[:q][:child_category_id]).map(&:id)
    elsif params[:q][:parent_category_id].present?
      child_category_ids = Category.child_num(params[:q][:parent_category_id]).map(&:id)
      grandchild_category_ids = Category.child_num(child_category_ids).map(&:id)
    end
    { category_id_eq_any: grandchild_category_ids }
  end

  def buyer_id_params
    if params[:q][:buyer_id_null].present? && params[:q][:buyer_id_not_null].present?
      { buyer_id_null: "" }
    elsif params[:q][:buyer_id_null].present?
      { buyer_id_null: true }
    elsif params[:q][:buyer_id_not_null].present?
      { buyer_id_not_null: true }
    end
  end
end

app/views/items/_footer.html.haml
.buy-page
  .buy-page__mypage-footer
    .buy-page__mypage-footer__text
      .buy-page__mypage-footer__text__word
        %p
          プライバシーポリシー
      .buy-page__mypage-footer__text__word
        %p
          メルカリ利用規約
      .buy-page__mypage-footer__text__word
        %p
          特定商取引に関わる表記
      .buy-page__mypage-footer__logo
        = link_to image_tag(src="//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3856598694"), root_path, class: 'get'
      .buy-page__mypage-footer__date
        %p
          © 2019 Mercari

app/views/items/_header.html.haml
.buy-page
  .buy-page__main-icon
    = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3270184656'

app/views/items/_item.html.haml
.like-link
  = render partial: 'likes/like_links', locals:{ item: item }

app/views/items/edit.html.haml
= render 'form', item: @item

app/views/items/new.html.haml
= render 'form', item: @item

app/views/items/search.html.haml
.breadcrumbs.solideee
  .breadcrumbs__style
    - breadcrumb :search
    = breadcrumbs separator: ""
%main
  .search-container
    .search-content
      = search_form_for @search, url: search_items_path ,html: {method: :post, class: 'search-form'} do |f|
        .search-form__item-sort
          .search-form__item-sort__pull-down
            = f.select( :sorts, { '並び替え': 'id desc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の古い順': 'updated_at asc', '出品の新しい順': 'updated_at desc', 'いいね!の多い順': 'likes_count desc' } , { selected: params[:q][:sorts] }, {class: "search-form__item-sort__pull-down__select", onchange: 'this.form.submit()'} )
            %i.fas.fa-chevron-down.search-form__item-sort__pull-down__icon
        .search-form__detail
          %h3.search-form__detail__head
            詳細検索
          .search-form__detail__keyword
            = f.label :name_or_description_cont, class: "search-form__detail__keyword__label" do
              %i.fas.fa-plus.search-form__detail__keyword__label__icon
              .search-form__detail__keyword__label__text
                キーワードを追加する
            = f.text_field :name_or_description_cont, placeholder: "例）値下げ", class: "search-form__detail__keyword__input"
          .search-form__detail__category
            = f.label :category_id, class: "search-form__detail__category__label" do
              %i.fas.fa-list-ul.search-form__detail__category__label__icon
              .search-form__detail__category__label__text
                カテゴリーを選択する
            .search-form__detail__category__pull-down.search-form__detail__category__pull-down--parent
              = f.collection_select( :parent_category_id, @parent_categories, :id, :name , {prompt: "すべて", selected: @parent_category_id}, { include_blank: true, class: "search-form__detail__category__pull-down__select", id: "parent_category_select-search" } )
              %i.fas.fa-chevron-down.search-form__detail__category__pull-down__icon.search-form__detail__category__pull-down__icon--parent
            .search-form__detail__category__pull-down.search-form__detail__category__pull-down--child
              = f.collection_select( :child_category_id, @child_categories, :id, :name ,{prompt: "すべて", selected: @child_category_id}, { include_blank: true, class: "search-form__detail__category__pull-down__select", id: "child_category_select-search" } )
              %i.fas.fa-chevron-down.search-form__detail__category__pull-down__icon.search-form__detail__category__pull-down__icon--child
            .search-form__detail__category__block
              = f.collection_check_boxes( :category_id_eq_any, @grandchild_categories, :id, :name, { include_hidden: false, include_blank: true, class: "search-form__detail__category__block__check-boxes", id: "grandchild_category_select-search" } ) do |b|
                = b.label(class: "search-form__detail__category__block__check-boxes__label") do
                  = b.check_box(class: "search-form__detail__category__block__check-boxes__label__input")
                  %i.fas.fa-check.check-icon.search-form__detail__category__block__check-boxes__label__icon
                  = b.label(class: "search-form__detail__category__block__check-boxes__label__text")
          .search-form__detail__brand
            = f.label :brnad, class: "search-form__detail__brand__label" do
              %i.fas.fa-tags.search-form__detail__brand__label__icon
              .search-form__detail__brand__label__text
                ブランド名から探す
            = f.text_field :brand_cont, placeholder: "例）シャネル", class: "search-form__detail__brand__input"
          .search-form__detail__size
            = f.label :size, class: "search-form__detail__size__label" do
              %i.fas.fa-vector-square.search-form__detail__size__label__icon
              .search-form__detail__size__label__text
                サイズを選択する
            .search-form__detail__size__pull-down
              = f.select( :size_eq, Item.sizes.map{|k, v| [Item.sizes_i18n[k], v]}, {prompt: "すべて"}, { class: "search-form__detail__size__pull-down__select"} )
              %i.fas.fa-chevron-down.search-form__detail__size__pull-down__icon
          .search-form__detail__price
            = f.label :size, class: "search-form__detail__price__label" do
              %i.fas.fa-coins.search-form__detail__price__label__icon
              .search-form__detail__price__label__text
                価格
            .search-form__detail__price__pull-down
              = f.select( :price, ["300~1000", "1000~5000", "5000~10000", "10000~30000", "30000~50000", "50000~"], {prompt: "選択して下さい"}, { class: "search-form__detail__price__pull-down__select"} )
              %i.fas.fa-chevron-down.search-form__detail__price__pull-down__icon
            .search-form__detail__price__inputs
              = f.text_field :price_gteq, placeholder: "¥ Min", class: "search-form__detail__price__inputs__min"
              %span.search-form__detail__price__inputs__wave
                &= "~"
              = f.text_field :price_lteq, placeholder: "¥ Max", class: "search-form__detail__price__inputs__max"
          .search-form__detail__condition
            = f.label :condition, class: "search-form__detail__condition__label" do
              %i.fas.fa-star.search-form__detail__condition__label__icon
              .search-form__detail__condition__label__text
                商品の状態
            .search-form__detail__condition__block
              = f.collection_check_boxes( :condition_eq_any, Item.conditions.map{|k, v| [Item.conditions_i18n[k], v]}, :last , :first , {include_hidden: false, class: "search-form__detail__condition__block__check-boxes"} ) do |b|
                = b.label(class: "search-form__detail__condition__block__check-boxes__label") do
                  = b.check_box(class: "search-form__detail__condition__block__check-boxes__label__input")
                  %i.fas.fa-check.check-icon.search-form__detail__condition__block__check-boxes__label__icon
                  = b.label(class: "search-form__detail__condition__block__check-boxes__label__text")
          .search-form__detail__postage
            = f.label :postage, class: "search-form__detail__postage__label" do
              %i.fas.fa-truck.search-form__detail__postage__label__icon
              .search-form__detail__postage__label__text
                配送料の負担
            .search-form__detail__postage__block
              = f.collection_check_boxes( :postage_eq_any, Item.postages.map{|k, v| [Item.postages_i18n[k], v]}, :last , :first , { class: "search-form__detail__postage__block__check-boxes"} ) do |b|
                = b.label(class: "search-form__detail__postage__block__check-boxes__label") do
                  = b.check_box(class: "search-form__detail__postage__block__check-boxes__label__input")
                  %i.fas.fa-check.check-icon.search-form__detail__postage__block__check-boxes__label__icon
                  = b.label(class: "search-form__detail__postage__block__check-boxes__label__text")
          .search-form__detail__sale
            = f.label :buyer_id, class: "search-form__detail__postage__label" do
              %i.fas.fa-shopping-cart.search-form__detail__sale__label__icon
              .search-form__detail__sale__label__text
                販売状況
            .search-form__detail__sale__block
              = f.label(:buyer_id_null, class: "search-form__detail__sale__block__check-boxes__label") do
                = f.check_box( :buyer_id_null, {class: "search-form__detail__sale__block__check-boxes__label__input"}, true, "")
                %i.fas.fa-check.check-icon.search-form__detail__sale__block__check-boxes__label__icon
                = f.label(:buyer_id_null, "販売中", class: "search-form__detail__sale__block__check-boxes__label__text")
              = f.label(:buyer_id_not_null, class: "search-form__detail__sale__block__check-boxes__label") do
                = f.check_box( :buyer_id_not_null, {class: "search-form__detail__sale__block__check-boxes__label__input"}, true, "")
                %i.fas.fa-check.check-icon.search-form__detail__sale__block__check-boxes__label__icon
                = f.label(:buyer_id_not_null, "売り切れ", class: "search-form__detail__sale__block__check-boxes__label__text")
          .search-form__detail__button
            = button_tag 'クリア', class: "search-form__detail__button__clear"
            = f.submit '完了', class: "search-form__detail__button__submit"

    .result-content
      .item-box-container
        %h2.item-box-head
          = search_result_title
        .search-result-number
          = @items.length.zero? ? "該当する商品が見つかりません。検索条件を変えて、再度お試しください。" : "1-#{@items.length}件表示"
        .item-box-content
          - @items = Item.limit(48).recent if @items.length == 0
          - @items.each do |item|
            .item-box
              = link_to item , class: 'item-box__link' do
                %figure.item-box__link__photo
                  = image_tag item.images[0].image.url
                  - if item.buyer_id.present?
                    .item-box__link__photo__mark
                      .item-box__link__photo__mark__red
                        SOLD
                .item-box__link__body
                  %h2.item-box__link__body__name
                    = item.name
                  .item-box__link__body__number
                    .item-box__link__body__number__price
                      = "¥#{item.price.to_s(:delimited)}"
                    - unless item.likes.count.zero?
                      %i.far.fa-heart
                      %span.item-box__link__body__number__like
                        = item.likes.count
                  .item-box__link__body__tax
                    (税込)

app/views/items/show.html.haml
.breadcrumbs.solideee
  .breadcrumbs__style
    - breadcrumb :products, @item
    = breadcrumbs separator: " #{content_tag(:i, '', class:'fas fa-chevron-right')} "

.product__details
  %h1.product__details-name
    = @item.name
  .product__details__item
    .product__details__item__image
      .product__details__item__image__big
        .product__details__item__image__big-overflow
          %ul.slick-main
            - @items.images.each do |img|
              %li.product__details__item__image__big-overflow-img
                = image_tag img.image.url
      .product__details__item__image-show
        .slider-nav
          - @items.images.each do |img|
            .product__details__item__image-show__box
              .product__details__item__image-show__box-image
                = image_tag img.image.url
    %table.product__details__item__table
      %tbody.product__details__item__table-t
        %tr
          %th 出品者
          %td
            =link_to @users.nickname, user_profiles_path(@users)
            .like
              .like-good
                %i.fas.fa-laugh
                230
              .like-normal
                %i.fas.fa-meh
                3
              .like-bad
                %i.fas.fa-frown
                1000
        %tr
          %th カテゴリー
          %td.font
            = link_to @theparent.name
            %br
            = link_to do
              %i.fas.fa-chevron-right
              = @child.name
            %br
            = link_to do
              %i.fas.fa-chevron-right
              = @groundchild.name
        %tr
          %th
            ブランド
          %td
            = @item.brand
        %tr
          %th 商品のサイズ
          %td
            - unless @item.size == "unanswered"
              = @item.size
        %tr
          %th 商品の状態
          %td
            = @item.condition_i18n
        %tr
          %th 発送料の負担
          %td
            = @item.postage_i18n
        %tr
          %th 発送の方法
          %td
            = @item.shipping_method_i18n
        %tr
          %th 発送元地域
          %td
            = @item.region_i18n
        %tr
          %th 発送日の目安
          %td
            = @items.shipping_date_i18n
  .product__details__price
    .product__details__price__box
      .product__details__price-en
        = "¥#{@items.price.to_s(:delimited)}"
      .product__details__price-tax
        (税込)
      .product__details__price-cost
        送料込み
  - if @items.buyer_id == nil
    -if user_signed_in? && current_user.id != @items.saler_id
      .product__details__btn
        %button
          =link_to '購入画面に進む',new_item_buy_order_path(@item.id)
  - else
    .product__details__btn-gray
      %button{disabled: "disabled"}売り切れました
  .product__details__text
    %p.product__details__text-inner
      = @item.description
  .product__details__bottom
    .product__details__bottom-left
      = render @item
    .product__details__bottom-right
      = link_to do
        %i.fas.fa-lock
        あんしん・あんぜんへの取り組み
-if @users.id == current_user.try(:id)
  -if @items.buyer_id == nil
    .chang-box
      %button.chang-box__btn-item-red
        = link_to "商品の編集", edit_item_path(@items.id)
      %p.chang-box__text-center
        or
      .wakeru
        = form_tag(stop_item_path(@item.id), method: :patch) do
          - if @item.status == false
            %input{type: "hidden",name: "status", value: 1}
            %button.chang-box__btn-item-gray{type: "submit"}
              出品を停止する
          - elsif @item.status == true
            %input{type: "hidden", name: "status", value: 0}
            %button.chang-box__btn-item-red{type: "submit"}
              出品停止中
      .wakeru2
        %button.chang-box__btn-item__gray
          = link_to 'この商品を削除する', item_path(@item.id), method: :delete

.comment
  .comment__content
    .comment__content__show
      %ul.comment__content__show-list
        -# 買う人のコメント
        %li.comment__content__show-list-left
          = link_to do
            %figure
              .div
                = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png"
              %figcaption name
          .con
            .con-text
              ここにコメントが入る
            .con-bottom
              .con-bottom-time
                %i.far.fa-clock
                74 日前
              .con-bottom-icon
                .delete-comment
                  %i.fas.fa-trash-alt
                %form
                  %button
                    %i.far.fa-flag
        -# %li.comment__content__show-list-left
          = link_to do
            %figure
              .div
                = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png"
              %figcaption name
          .con
            .con-text
              コメントコメントコメントコメントコメントコメントコメントコメントコメントコメントコメントコメントコメント
            .con-bottom
              .con-bottom-time
                %i.far.fa-clock
                74 日前
              .con-bottom-icon
                .delete-comment
                  %i.fas.fa-trash-alt
                %form
                  %button
                    %i.far.fa-flag
        -# 売る人のコメント
        %li.comment__content__show-list-right
          = link_to do
            %figure
          .con
            .con-text
            .con-bottom
              .con-bottom-time
              .con-bottom-icon
    .comment__content__form
      %form.comment__content__form__comment
        %p.comment__content__form__comment-caution
          相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %textarea.comment__content__form__comment-text
        %button.comment__content__form__comment-btn
          コメントする

%main
  .container.backgroundf5f5f5
    .content-mypage-detail
      .social-media-box
        %ul.social-media-box__lists
          %li.social-media-box__lists__icon.social-media-box__lists__icon--facebook
            = link_to "#" do
              %i.fab.fa-facebook-square
          %li.social-media-box__lists__icon.social-media-box__lists__icon--twitter
            = link_to "#" do
              %i.fab.fa-twitter
          %li.social-media-box__lists__icon.social-media-box__lists__icon--line
            = link_to "#" do
              %i.fab.fa-line
      .item-box-container.backgroundf5f5f5
        %h2.item-box-head.padding24px
          この出品者の商品
        .item-box-content
          - @slaer_items.each do |item|
            .item-box.backgroundfff
              = link_to item_path(item.id), class: 'item-box__link' do
                %figure.item-box__link__photo
                  = image_tag item.images[0].image.url
                .item-box__link__body
                  %h2.item-box__link__body__description
                    = item.name
                  .item-box__link__body__number
                    .item-box__link__body__number__price
                      = "¥ #{item.price.to_s(:delimited)}"
                    %i.far.fa-heart
                    %span.item-box__link__body__number__like
                      2
                  .item-box__link__body__tax
                    (税込)