config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: [:show, :edit, :new] do
    resource :profiles, only: [:show, :edit]
    resource :addresses, only: [:new,:edit,:create]
    collection do
      get 'address'
      get 'card'
      get 'telephone'
      get 'complete'
    end
    member do
      get 'logout'
      patch 'logout'
    end
    resource :cards, only: [:show, :new] do
      collection do
        post "pay", to: "cards#pay"
        post "delete", to: "cards#delete"
      end
    end
  end

  resources :items do
    get "search", on: :collection
    member do
      patch 'stop'
    end
    resources :images
    resources :likes
    resources :comments
    resources :buy_orders, only: :new do
      collection do
        post 'index', to: 'buy_orders#pay'
        post 'pay', to: "buy_order#pay"
      end
    end
  end
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end

  resources :categories, only: :index
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"
  before_action :set_card

  def new
  end

  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(card: params['payjp-token']) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to user_cards_path(@card.user_id)
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    if @card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
    redirect_to user_cards_path(@card.user_id)
  end

  def show
    if @card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  private

  def set_card
    @card = Card.where(user_id: current_user.id).first
    @user = User.find(params[:user_id])
  end
end

app/views/cards/destroy.html.haml
.user
  .user__logout
    .user__logout-button
      %button
        = link_to "ログアウト", "url", method: :delete

app/views/cards/edit.html.haml
%main
  %div

app/views/cards/new.html.haml
.breadcrumbs.solideee
  .breadcrumbs__style
    - breadcrumb :card_input
    = breadcrumbs separator: " #{content_tag(:i, '', class:'fas fa-chevron-right')} "
%main
  .container
    .content
      %h2 クレジットカード情報入力
      = form_tag("/users/#{current_user.id}/cards/pay", class: "form", method: :post, id: 'charge-form', name: "inputForm") do
        .content__input
          .content__input__info
            .content__input__info-num
              %label
                カード番号
                %span.required
                  必須
              = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
              %ul
                %li
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3856598694"
                %li
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?3856598694"
                %li
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?3856598694"
                %li
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?3856598694"
                %li
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?3856598694"
                %li
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?3856598694"
                %li
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?3856598694"
            .content__input__info-limit
              %label
                有効期限
                %span.required
                  必須
              .limit-moth
                %select#exp_month{name: "exp_month", type: "text"}
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                %i#down.fas.fa-chevron-down
                %span 月
              .limit-year
                %select#exp_year{name: "exp_year", type: "text"}
                  %option{value: ""} --
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                %i#down.fas.fa-chevron-down
                %span 年
            .content__input__info-security
              %label
                セキュリティーコード
                %span.required
                  必須
              = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              .sec_info
                %p カード裏面の番号とは？
            .content__input__info-btn#card_token
              = button_tag "追加する", id: "token_submit", class: "submit-button"

    .side
      = render "layouts/side"

app/views/cards/show.html.haml
.breadcrumbs.solideee
  .breadcrumbs__style
    - breadcrumb :card
    = breadcrumbs separator: " #{content_tag(:i, '', class:'fas fa-chevron-right')} "
%main
  .container
    .content
      %h2 支払い方法
      .form
        .content__card
          %section.content__card-a
            .content__card-a-index
              %h3 クレジットカード一覧
            .content__card-a-show
              - unless @card == nil
                %ul
                  %li
                    %figure
                      = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3856598694"
                    .show-num
                      = "**** **** **** " + @default_card_information.last4
                    .show-day
                      - exp_month = @default_card_information.exp_month.to_s
                      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                      = exp_month + " / " + exp_year
                    .show-button
                      = form_tag(delete_user_cards_path(@card.user_id), method: :post, id: 'charge-form',  name: "inputForm") do
                        %input{ type: "hidden", name: "card_id", value: "" }
                        %button 削除する
          %section.content__card-b
            - if @card == nil
              .content__card-b-btn
                %button 
                  = link_to new_user_cards_path(current_user.id), class: "btn" do
                    %i.far.fa-credit-card クレジットカードを追加する
            .content__card-link
              = link_to do
                支払い方法について
                %i.fas.fa-chevron-right
    .side
      = render "layouts/side"